<a href="https://colab.research.google.com/github/theannshu/theannshu/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ** 	Assignment 3**
   Course: Foundation of Data Analytics
# **________________________________________**

# **Question 1.**

Download two datasets(in .csv format) that were not used previously in assignments. Describe

Note: Use Kaggle or UCI Machine Learning Repository.
        
# 1.	**About Dataset (Example: Iris data is about flower and their parts. Use of this data.)**

Ans. - **Dataset 1 is about ufc fighter statistics.And Dataset 2 is about players data.**

# 2.	Number of records

**Of dataset 1**- ufc fighter statistics

In [11]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/dataset 1/ufc-fighters-statistics.csv")
num_records = len(df)
print(f"Number of records in dataset 1 is :{num_records}")

Number of records in dataset 1 is :4109

**Of dataset 2 - Players data**

In [12]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dataset 2/player_data_03_22.csv")
num_records = len(df)
print(f"Number of records in dataset 2 is :{num_records}")

Number of records in dataset 2 is :9660

## **3.	Number of columns and describe all.**

# **Of dataset 1**

In [17]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dataset 1/ufc-fighters-statistics.csv")
num_columns = len(df.columns)
print(f'Number of column in dataset 1 is : {num_columns}')
description = df.describe()
print(description)

Number of column in dataset 1 is : 18
              wins       losses        draws    height_cm  weight_in_kg  \
count  4109.000000  4109.000000  4109.000000  3812.000000   4022.000000
mean     12.360672     5.722073     0.264298   178.234439     77.395405
std       9.376023     5.104569     0.822483     8.889213     17.988389
min       0.000000     0.000000     0.000000   152.400000     47.630000
25%       7.000000     2.000000     0.000000   172.720000     65.770000
50%      11.000000     4.000000     0.000000   177.800000     77.110000
75%      17.000000     8.000000     0.000000   185.420000     83.910000
max     253.000000    83.000000    11.000000   226.060000    349.270000

       reach_in_cm  significant_strikes_landed_per_minute  \
count  2183.000000                            4109.000000
mean    181.803729                               2.442100
std      10.679990                               1.996586
min     147.320000                               0.000000
25%     175.260000                               0.830000
50%     182.880000                               2.330000
75%     190.500000                               3.600000
max     213.360000                              17.650000

       significant_striking_accuracy  significant_strikes_absorbed_per_minute  \
count                    4109.000000                              4109.000000
mean                       35.553906                                 3.146878
std                        20.405083                                 2.850083
min                         0.000000                                 0.000000
25%                        27.000000                                 1.550000
50%                        40.000000                                 2.940000
75%                        49.000000                                 4.240000
max                       100.000000                                52.500000

       significant_strike_defence  average_takedowns_landed_per_15_minutes  \
count                 4109.000000                              4109.000000
mean                    42.666586                                 1.248537
std                     22.323827                                 1.931608
min                      0.000000                                 0.000000
25%                     36.000000                                 0.000000
50%                     50.000000                                 0.590000
75%                     58.000000                                 1.930000
max                    100.000000                                32.140000

       takedown_accuracy  takedown_defense  \
count        4109.000000       4109.000000
mean           26.296666         39.015332
std            28.728565         34.457155
min             0.000000          0.000000
25%             0.000000          0.000000
50%            22.000000         42.000000
75%            45.000000         66.000000
max           100.000000        100.000000

       average_submissions_attempted_per_15_minutes
count                                   4109.000000
mean                                       2.442100
std                                        1.996586
min                                        0.000000
25%                                        0.830000
50%                                        2.330000
75%                                        3.600000
max                                       17.650000

# **Of dataset 2**

In [18]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dataset 2/player_data_03_22.csv")
num_columns = len(df.columns)

description = df.describe()
print(f'Number of column in dataset 1 is : {num_columns}')
print(description)

Number of column in dataset 1 is : 42
                 0          Age            G           GS           MP  \
count  9660.000000  9660.000000  9660.000000  9660.000000  9660.000000
mean   4829.500000    26.393685    51.363147    24.798447    20.178520
std    2788.746134     4.265612    24.971391    28.400407     9.806724
min       0.000000    18.000000     1.000000     0.000000     0.000000
25%    2414.750000    23.000000    31.000000     1.000000    12.200000
50%    4829.500000    26.000000    58.000000    10.000000    19.600000
75%    7244.250000    29.000000    73.000000    49.000000    28.200000
max    9659.000000    44.000000    85.000000    83.000000    43.500000

                FG          FGA          FG%           3P          3PA  ...  \
count  9660.000000  9660.000000  9660.000000  9660.000000  9660.000000  ...
mean      3.078395     6.855176     0.436926     0.655342     1.874037  ...
std       2.179313     4.609273     0.101986     0.734343     1.927487  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       1.400000     3.300000     0.399000     0.000000     0.100000  ...
50%       2.600000     5.800000     0.438000     0.400000     1.300000  ...
75%       4.300000     9.500000     0.483000     1.100000     3.100000  ...
max      12.200000    27.200000     1.000000     5.300000    13.200000  ...

           Pts Won      Pts Max        Share            W            L  \
count  9660.000000  9660.000000  9660.000000  9660.000000  9660.000000
mean      6.314700    33.577640     0.005382    39.841925    40.187060
std      67.843467   197.024705     0.057647    12.317190    12.220466
min       0.000000     0.000000     0.000000     7.000000     9.000000
25%       0.000000     0.000000     0.000000    31.000000    31.000000
50%       0.000000     0.000000     0.000000    41.000000    40.000000
75%       0.000000     0.000000     0.000000    49.000000    49.000000
max    1310.000000  1310.000000     1.000000    73.000000    72.000000

              W/L%           GB         PS/G         PA/G          SRS
count  9660.000000  9660.000000  9660.000000  9660.000000  9660.000000
mean      0.497579    14.594669   102.196718   102.277536    -0.080583
std       0.150345    12.700769     7.084795     7.093605     4.475561
min       0.106000     0.000000    84.200000    84.300000   -13.960000
25%       0.390000     3.000000    96.900000    97.000000    -3.120000
50%       0.512000    12.000000   101.400000   101.500000    -0.040000
75%       0.610000    24.000000   107.050000   107.300000     3.122500
max       0.890000    56.000000   120.100000   119.700000    11.350000

[8 rows x 38 columns]

# **4.	Check and remove NULL values using dropna() and fillna() (with mean, median, and mode).**

# **of Dataset 1**

In [22]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dataset 1/ufc-fighters-statistics.csv")
null_values = df.isnull().sum()
print("Null values in each column :\n", null_values)
df_dropped = df.dropna()

df_filled_mean = df.fillna(df.mean())
df_filled_median = df.fillna(df.median())
df_filled_mode = df.fillna(df.mode().iloc[0])

print("\nDataFrame after dropping NULL values:\n", df_dropped)
print("\nDataframe after filling NULL values with mean:\n", df_filled_mean)
print("\nDataframe after fillimg NULL values with median:\n", df_filled_median)
print("\nDataframe after filling NULL values with mode:\n", df_filled_mode)

Null values in each column :
 name                                               0
nickname                                        1854
wins                                               0
losses                                             0
draws                                              0
height_cm                                        297
weight_in_kg                                      87
reach_in_cm                                     1926
stance                                           822
date_of_birth                                   1134
significant_strikes_landed_per_minute              0
significant_striking_accuracy                      0
significant_strikes_absorbed_per_minute            0
significant_strike_defence                         0
average_takedowns_landed_per_15_minutes            0
takedown_accuracy                                  0
takedown_defense                                   0
average_submissions_attempted_per_15_minutes       0
dtype: int64

DataFrame after dropping NULL values:
                        name                  nickname  wins  losses  draws  \
2        Cortavious Romious  Are You Not Entertained?     7       2      0
3               Danny Silva                   El Puma     8       1      0
5     Charalampos Grigoriou                 Ferocious     8       3      0
7        Ernesta Kareckaite              Heavy-Handed     5       0      1
8              Danny Barlow              LeftHand2God     7       0      0
...                     ...                       ...   ...     ...    ...
3957      Sho Patrick Usami                    Savage     4       1      0
3980          Ivan Shtyrkov                 Ural Hulk    15       0      1
4050             MinWoo Kim               Korean MOAI    10       2      0
4068            Askar Askar                     AK-47    11       1      0
4108          Shaun Etchell               The Buzzsaw     7       3      0

      height_cm  weight_in_kg  reach_in_cm    stance date_of_birth  \
2        162.56         61.23       172.72  Southpaw    1994-01-06
3        180.34         65.77       177.80    Switch    1997-01-30
5        170.18         61.23       170.18  Orthodox    1992-03-31
7        175.26         56.70       180.34  Orthodox    1998-07-05
8        187.96         77.11       200.66  Southpaw    1995-08-02
...         ...           ...          ...       ...           ...
3957     175.26         70.31       177.80  Orthodox    2000-05-08
3980     182.88         92.99       187.96  Orthodox    1988-06-09
4050     172.72         61.23       182.88  Orthodox    1993-07-21
4068     170.18         65.77       175.26  Orthodox    1994-08-19
4108     170.18         56.70       172.72    Switch    1993-08-05

      significant_strikes_landed_per_minute  significant_striking_accuracy  \
2                                     14.48                           31.0
3                                     13.60                           64.0
5                                     13.00                           65.0
7                                     12.27                           45.0
8                                     12.15                           57.0
...                                     ...                            ...
3957                                   0.00                            0.0
3980                                   0.00                            0.0
4050                                   0.00                            0.0
4068                                   0.00                            0.0
4108                                   0.00                            0.0

      significant_strikes_absorbed_per_minute  significant_strike_defence  \
2                                       20.69                        41.0
3                                       13.13                        59.0
5                                        4.00                        63.0
7                                       11.20                        42.0
8                                        5.32                        61.0
...                                       ...                         ...
3957                                     0.00                         0.0
3980                                     0.00                         0.0
4050                                     0.00                         0.0
4068                                     0.00                         0.0
4108                                     0.00                         0.0

      average_takedowns_landed_per_15_minutes  takedown_accuracy  \
2                                        0.00                0.0
3                                        2.00               66.0
5                                        0.00                0.0
7                                        1.00               50.0
8                                        0.00                0.0
...                                       ...                ...
3957                                     0.00                0.0
3980                                     0.00                0.0
4050                                     0.00                0.0
4068                                     0.00                0.0
4108                                     4.37              100.0

      takedown_defense  average_submissions_attempted_per_15_minutes
2                  0.0                                         14.48
3                100.0                                         13.60
5                  0.0                                         13.00
7                100.0                                         12.27
8                  0.0                                         12.15
...                ...                                           ...
3957               0.0                                          0.00
3980               0.0                                          0.00
4050               0.0                                          0.00
4068               0.0                                          0.00
4108             100.0                                          0.00

[1504 rows x 18 columns]

Dataframe after filling NULL values with mean:
                     name                  nickname  wins  losses  draws  \
0           Rex Richards                       NaN     7       2      0
1           Luana Santos                       NaN     6       1      0
2     Cortavious Romious  Are You Not Entertained?     7       2      0
3            Danny Silva                   El Puma     8       1      0
4          Angel Pacheco                       NaN     7       2      0
...                  ...                       ...   ...     ...    ...
4104      Edgar Cardenas                Kitty Katt     4       1      0
4105           Joe Veres                       NaN     4       3      0
4106      Jordan Goodwin                       NaN     0       0      0
4107     Robert Drysdale                       NaN     7       0      0
4108       Shaun Etchell               The Buzzsaw     7       3      0

       height_cm  weight_in_kg  reach_in_cm    stance date_of_birth  \
0     195.580000        120.20   181.803729       NaN           NaN
1     167.640000         56.70   170.180000  Orthodox    2000-04-16
2     162.560000         61.23   172.720000  Southpaw    1994-01-06
3     180.340000         65.77   177.800000    Switch    1997-01-30
4     172.720000         65.77   177.800000  Orthodox    1992-01-13
...          ...           ...          ...       ...           ...
4104  178.234439         65.77   181.803729       NaN           NaN
4105  170.180000         70.31   181.803729  Orthodox    1977-11-09
4106  178.234439         70.31   181.803729       NaN           NaN
4107  190.500000         92.99   181.803729  Orthodox    1981-10-05
4108  170.180000         56.70   172.720000    Switch    1993-08-05

      significant_strikes_landed_per_minute  significant_striking_accuracy  \
0                                     17.65                           58.0
1                                     17.10                           60.0
2                                     14.48                           31.0
3                                     13.60                           64.0
4                                     13.13                           40.0
...                                     ...                            ...
4104                                   0.00                            0.0
4105                                   0.00                            0.0
4106                                   0.00                            0.0
4107                                   0.00                            0.0
4108                                   0.00                            0.0

      significant_strikes_absorbed_per_minute  significant_strike_defence  \
0                                        5.29                        72.0
1                                        6.52                        68.0
2                                       20.69                        41.0
3                                       13.13                        59.0
4                                       13.60                        35.0
...                                       ...                         ...
4104                                     0.00                         0.0
4105                                     5.55                        27.0
4106                                     0.00                         0.0
4107                                     0.00                         0.0
4108                                     0.00                         0.0

      average_takedowns_landed_per_15_minutes  takedown_accuracy  \
0                                        0.00                0.0
1                                        0.00                0.0
2                                        0.00                0.0
3                                        2.00               66.0
4                                        0.00                0.0
...                                       ...                ...
4104                                     0.00                0.0
4105                                     0.00                0.0
4106                                     0.00                0.0
4107                                     7.32              100.0
4108                                     4.37              100.0

      takedown_defense  average_submissions_attempted_per_15_minutes
0                  0.0                                         17.65
1                100.0                                         17.10
2                  0.0                                         14.48
3                100.0                                         13.60
4                 33.0                                         13.13
...                ...                                           ...
4104               0.0                                          0.00
4105               0.0                                          0.00
4106               0.0                                          0.00
4107               0.0                                          0.00
4108             100.0                                          0.00

[4109 rows x 18 columns]

Dataframe after fillimg NULL values with median:
                     name                  nickname  wins  losses  draws  \
0           Rex Richards                       NaN     7       2      0
1           Luana Santos                       NaN     6       1      0
2     Cortavious Romious  Are You Not Entertained?     7       2      0
3            Danny Silva                   El Puma     8       1      0
4          Angel Pacheco                       NaN     7       2      0
...                  ...                       ...   ...     ...    ...
4104      Edgar Cardenas                Kitty Katt     4       1      0
4105           Joe Veres                       NaN     4       3      0
4106      Jordan Goodwin                       NaN     0       0      0
4107     Robert Drysdale                       NaN     7       0      0
4108       Shaun Etchell               The Buzzsaw     7       3      0

      height_cm  weight_in_kg  reach_in_cm    stance date_of_birth  \
0        195.58        120.20       182.88       NaN           NaN
1        167.64         56.70       170.18  Orthodox    2000-04-16
2        162.56         61.23       172.72  Southpaw    1994-01-06
3        180.34         65.77       177.80    Switch    1997-01-30
4        172.72         65.77       177.80  Orthodox    1992-01-13
...         ...           ...          ...       ...           ...
4104     177.80         65.77       182.88       NaN           NaN
4105     170.18         70.31       182.88  Orthodox    1977-11-09
4106     177.80         70.31       182.88       NaN           NaN
4107     190.50         92.99       182.88  Orthodox    1981-10-05
4108     170.18         56.70       172.72    Switch    1993-08-05

      significant_strikes_landed_per_minute  significant_striking_accuracy  \
0                                     17.65                           58.0
1                                     17.10                           60.0
2                                     14.48                           31.0
3                                     13.60                           64.0
4                                     13.13                           40.0
...                                     ...                            ...
4104                                   0.00                            0.0
4105                                   0.00                            0.0
4106                                   0.00                            0.0
4107                                   0.00                            0.0
4108                                   0.00                            0.0

      significant_strikes_absorbed_per_minute  significant_strike_defence  \
0                                        5.29                        72.0
1                                        6.52                        68.0
2                                       20.69                        41.0
3                                       13.13                        59.0
4                                       13.60                        35.0
...                                       ...                         ...
4104                                     0.00                         0.0
4105                                     5.55                        27.0
4106                                     0.00                         0.0
4107                                     0.00                         0.0
4108                                     0.00                         0.0

      average_takedowns_landed_per_15_minutes  takedown_accuracy  \
0                                        0.00                0.0
1                                        0.00                0.0
2                                        0.00                0.0
3                                        2.00               66.0
4                                        0.00                0.0
...                                       ...                ...
4104                                     0.00                0.0
4105                                     0.00                0.0
4106                                     0.00                0.0
4107                                     7.32              100.0
4108                                     4.37              100.0

      takedown_defense  average_submissions_attempted_per_15_minutes
0                  0.0                                         17.65
1                100.0                                         17.10
2                  0.0                                         14.48
3                100.0                                         13.60
4                 33.0                                         13.13
...                ...                                           ...
4104               0.0                                          0.00
4105               0.0                                          0.00
4106               0.0                                          0.00
4107               0.0                                          0.00
4108             100.0                                          0.00

[4109 rows x 18 columns]

Dataframe after filling NULL values with mode:
                     name                  nickname  wins  losses  draws  \
0           Rex Richards                 The Beast     7       2      0
1           Luana Santos                 The Beast     6       1      0
2     Cortavious Romious  Are You Not Entertained?     7       2      0
3            Danny Silva                   El Puma     8       1      0
4          Angel Pacheco                 The Beast     7       2      0
...                  ...                       ...   ...     ...    ...
4104      Edgar Cardenas                Kitty Katt     4       1      0
4105           Joe Veres                 The Beast     4       3      0
4106      Jordan Goodwin                 The Beast     0       0      0
4107     Robert Drysdale                 The Beast     7       0      0
4108       Shaun Etchell               The Buzzsaw     7       3      0

      height_cm  weight_in_kg  reach_in_cm    stance date_of_birth  \
0        195.58        120.20       182.88  Orthodox    1987-01-21
1        167.64         56.70       170.18  Orthodox    2000-04-16
2        162.56         61.23       172.72  Southpaw    1994-01-06
3        180.34         65.77       177.80    Switch    1997-01-30
4        172.72         65.77       177.80  Orthodox    1992-01-13
...         ...           ...          ...       ...           ...
4104     182.88         65.77       182.88  Orthodox    1987-01-21
4105     170.18         70.31       182.88  Orthodox    1977-11-09
4106     182.88         70.31       182.88  Orthodox    1987-01-21
4107     190.50         92.99       182.88  Orthodox    1981-10-05
4108     170.18         56.70       172.72    Switch    1993-08-05

      significant_strikes_landed_per_minute  significant_striking_accuracy  \
0                                     17.65                           58.0
1                                     17.10                           60.0
2                                     14.48                           31.0
3                                     13.60                           64.0
4                                     13.13                           40.0
...                                     ...                            ...
4104                                   0.00                            0.0
4105                                   0.00                            0.0
4106                                   0.00                            0.0
4107                                   0.00                            0.0
4108                                   0.00                            0.0

      significant_strikes_absorbed_per_minute  significant_strike_defence  \
0                                        5.29                        72.0
1                                        6.52                        68.0
2                                       20.69                        41.0
3                                       13.13                        59.0
4                                       13.60                        35.0
...                                       ...                         ...
4104                                     0.00                         0.0
4105                                     5.55                        27.0
4106                                     0.00                         0.0
4107                                     0.00                         0.0

<ipython-input-22-32d75a5e436c>:7: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_mean = df.fillna(df.mean())
<ipython-input-22-32d75a5e436c>:8: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_median = df.fillna(df.median())

# **Of dataset 2**

In [23]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/dataset 2/player_data_03_22.csv")
null_values = df.isnull().sum()
print("Null values in each column :\n", null_values)
df_dropped = df.dropna()

df_filled_mean = df.fillna(df.mean())
df_filled_median = df.fillna(df.median())
df_filled_mode = df.fillna(df.mode().iloc[0])

print("\nDataFrame after dropping NULL values:\n", df_dropped)
print("\nDataframe after filling NULL values with mean:\n", df_filled_mean)
print("\nDataframe after fillimg NULL values with median:\n", df_filled_median)
print("\nDataframe after filling NULL values with mode:\n", df_filled_mode)

Null values in each column :
 0          0
Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
Team       0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
dtype: int64

DataFrame after dropping NULL values:
          0          Player Pos  Age   Tm   G  GS    MP   FG   FGA  ...  \
0        0     A.J. Guyton  PG   24  GSW   2   0   4.5  0.0   2.0  ...
1        1    Adonal Foyle   C   27  GSW  82   0  21.8  2.3   4.2  ...
2        2  Antawn Jamison  SF   26  GSW  82  82  39.3  8.4  17.9  ...
3        3        Bob Sura  SG   29  GSW  55   0  20.5  2.5   6.0  ...
4        4     Chris Mills  PF   33  GSW  21   0  12.5  1.9   5.0  ...
...    ...             ...  ..  ...  ...  ..  ..   ...  ...   ...  ...
9655  9655   Spencer Hawes  PF   28  MIL  54   1  14.8  2.5   5.1  ...
9656  9656     Steve Novak  PF   33  MIL   8   0   2.8  0.3   0.9  ...
9657  9657  Terrence Jones  PF   25  MIL  54  12  23.5  4.3   9.1  ...
9658  9658      Thon Maker   C   19  MIL  57  34   9.9  1.5   3.2  ...
9659  9659      Tony Snell  SG   25  MIL  80  80  29.2  3.1   6.8  ...

      Pts Max  Share                   Team   W   L   W/L%    GB   PS/G  \
0           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
1           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
2           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
3           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
4           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
...       ...    ...                    ...  ..  ..    ...   ...    ...
9655        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9656        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9657        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9658        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9659        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6

       PA/G   SRS
0     103.6 -0.60
1     103.6 -0.60
2     103.6 -0.60
3     103.6 -0.60
4     103.6 -0.60
...     ...   ...
9655  103.8 -0.45
9656  103.8 -0.45
9657  103.8 -0.45
9658  103.8 -0.45
9659  103.8 -0.45

[9660 rows x 42 columns]

Dataframe after filling NULL values with mean:
          0          Player Pos  Age   Tm   G  GS    MP   FG   FGA  ...  \
0        0     A.J. Guyton  PG   24  GSW   2   0   4.5  0.0   2.0  ...
1        1    Adonal Foyle   C   27  GSW  82   0  21.8  2.3   4.2  ...
2        2  Antawn Jamison  SF   26  GSW  82  82  39.3  8.4  17.9  ...
3        3        Bob Sura  SG   29  GSW  55   0  20.5  2.5   6.0  ...
4        4     Chris Mills  PF   33  GSW  21   0  12.5  1.9   5.0  ...
...    ...             ...  ..  ...  ...  ..  ..   ...  ...   ...  ...
9655  9655   Spencer Hawes  PF   28  MIL  54   1  14.8  2.5   5.1  ...
9656  9656     Steve Novak  PF   33  MIL   8   0   2.8  0.3   0.9  ...
9657  9657  Terrence Jones  PF   25  MIL  54  12  23.5  4.3   9.1  ...
9658  9658      Thon Maker   C   19  MIL  57  34   9.9  1.5   3.2  ...
9659  9659      Tony Snell  SG   25  MIL  80  80  29.2  3.1   6.8  ...

      Pts Max  Share                   Team   W   L   W/L%    GB   PS/G  \
0           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
1           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
2           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
3           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
4           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
...       ...    ...                    ...  ..  ..    ...   ...    ...
9655        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9656        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9657        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9658        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9659        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6

       PA/G   SRS
0     103.6 -0.60
1     103.6 -0.60
2     103.6 -0.60
3     103.6 -0.60
4     103.6 -0.60
...     ...   ...
9655  103.8 -0.45
9656  103.8 -0.45
9657  103.8 -0.45
9658  103.8 -0.45
9659  103.8 -0.45

[9660 rows x 42 columns]

Dataframe after fillimg NULL values with median:
          0          Player Pos  Age   Tm   G  GS    MP   FG   FGA  ...  \
0        0     A.J. Guyton  PG   24  GSW   2   0   4.5  0.0   2.0  ...
1        1    Adonal Foyle   C   27  GSW  82   0  21.8  2.3   4.2  ...
2        2  Antawn Jamison  SF   26  GSW  82  82  39.3  8.4  17.9  ...
3        3        Bob Sura  SG   29  GSW  55   0  20.5  2.5   6.0  ...
4        4     Chris Mills  PF   33  GSW  21   0  12.5  1.9   5.0  ...
...    ...             ...  ..  ...  ...  ..  ..   ...  ...   ...  ...
9655  9655   Spencer Hawes  PF   28  MIL  54   1  14.8  2.5   5.1  ...
9656  9656     Steve Novak  PF   33  MIL   8   0   2.8  0.3   0.9  ...
9657  9657  Terrence Jones  PF   25  MIL  54  12  23.5  4.3   9.1  ...
9658  9658      Thon Maker   C   19  MIL  57  34   9.9  1.5   3.2  ...
9659  9659      Tony Snell  SG   25  MIL  80  80  29.2  3.1   6.8  ...

      Pts Max  Share                   Team   W   L   W/L%    GB   PS/G  \
0           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
1           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
2           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
3           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
4           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
...       ...    ...                    ...  ..  ..    ...   ...    ...
9655        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9656        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9657        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9658        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9659        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6

       PA/G   SRS
0     103.6 -0.60
1     103.6 -0.60
2     103.6 -0.60
3     103.6 -0.60
4     103.6 -0.60
...     ...   ...
9655  103.8 -0.45
9656  103.8 -0.45
9657  103.8 -0.45
9658  103.8 -0.45
9659  103.8 -0.45

[9660 rows x 42 columns]

Dataframe after filling NULL values with mode:
          0          Player Pos  Age   Tm   G  GS    MP   FG   FGA  ...  \
0        0     A.J. Guyton  PG   24  GSW   2   0   4.5  0.0   2.0  ...
1        1    Adonal Foyle   C   27  GSW  82   0  21.8  2.3   4.2  ...
2        2  Antawn Jamison  SF   26  GSW  82  82  39.3  8.4  17.9  ...
3        3        Bob Sura  SG   29  GSW  55   0  20.5  2.5   6.0  ...
4        4     Chris Mills  PF   33  GSW  21   0  12.5  1.9   5.0  ...
...    ...             ...  ..  ...  ...  ..  ..   ...  ...   ...  ...
9655  9655   Spencer Hawes  PF   28  MIL  54   1  14.8  2.5   5.1  ...
9656  9656     Steve Novak  PF   33  MIL   8   0   2.8  0.3   0.9  ...
9657  9657  Terrence Jones  PF   25  MIL  54  12  23.5  4.3   9.1  ...
9658  9658      Thon Maker   C   19  MIL  57  34   9.9  1.5   3.2  ...
9659  9659      Tony Snell  SG   25  MIL  80  80  29.2  3.1   6.8  ...

      Pts Max  Share                   Team   W   L   W/L%    GB   PS/G  \
0           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
1           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
2           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
3           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
4           0    0.0  Golden State Warriors  38  44  0.463  21.0  102.4
...       ...    ...                    ...  ..  ..    ...   ...    ...
9655        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9656        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9657        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9658        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6
9659        0    0.0        Milwaukee Bucks  42  40  0.512   9.0  103.6

       PA/G   SRS
0     103.6 -0.60
1     103.6 -0.60
2     103.6 -0.60
3     103.6 -0.60
4     103.6 -0.60
...     ...   ...
9655  103.8 -0.45
9656  103.8 -0.45
9657  103.8 -0.45
9658  103.8 -0.45
9659  103.8 -0.45

[9660 rows x 42 columns]

<ipython-input-23-fbf40d91cc52>:7: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_mean = df.fillna(df.mean())
<ipython-input-23-fbf40d91cc52>:8: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_median = df.fillna(df.median())

# **5.	Normalize data in the range 0 to 1**